import { useEffect, useState, type FormEvent } from "react";
import { useServerFn } from "@tanstack/react-start";
import { ArrowUpRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { submitLead } from "@/lib/leads.functions";
import { submitLeadForm, type LeadInput } from "@/lib/lead-form-client";
import type { Locale } from "@/lib/site-locale";
const fieldClass = "h-12 rounded-none border-x-0 border-t-0 border-input bg-transparent px-0 text-foreground placeholder:text-muted-foreground focus-visible:border-gold focus-visible:ring-0";
type LeadInterest = "start" | "clasic" | "full_social" | "free_ideas" | "unsure";
const formCopy = { ro: { success:"Solicitarea a fost trimisă. Revenim cu un răspuns.", error:"Nu am putut trimite solicitarea. Verifică datele și încearcă din nou.", name:"Nume *", business:"Numele businessului", interest:"CE TE INTERESEAZĂ?", free:"3 IDEI GRATUITE", talk:"VREAU SĂ DISCUTĂM", phone:"Telefon", message:"Spune-ne pe scurt despre business și ce vrei să obții.", consent:"Sunt de acord să fiu contactat în legătură cu solicitarea mea.", sending:"SE TRIMITE...", send:"TRIMITE SOLICITAREA" }, en: { success:"Your enquiry has been sent. We’ll be in touch.", error:"We couldn’t send your enquiry. Please check your details and try again.", name:"Name *", business:"Business name", interest:"WHAT ARE YOU INTERESTED IN?", free:"3 COMPLIMENTARY IDEAS", talk:"I’D LIKE TO TALK", phone:"Phone", message:"Tell us briefly about your business and what you want to achieve.", consent:"I agree to be contacted about my enquiry.", sending:"SENDING...", send:"SEND ENQUIRY" } } as const;
function FormStatus({ state, locale }: { state:"idle"|"sending"|"success"|"error"; locale:Locale }) { const t=formCopy[locale]; if(state==="success") return <p role="status" className="mt-5 text-sm text-gold">{t.success}</p>; if(state==="error") return <p role="alert" className="mt-5 text-sm text-destructive">{t.error}</p>; return null; }
export function ContactForm({ locale = "ro" }: { locale?: Locale }) {
 const sendLead=useServerFn(submitLead); const [interest,setInterest]=useState<LeadInterest>("clasic"); const [consent,setConsent]=useState(false); const [state,setState]=useState<"idle"|"sending"|"success"|"error">("idle"); const t=formCopy[locale];
 useEffect(()=>{ const sync=(event?:Event)=>{ const detail=event instanceof CustomEvent?event.detail:undefined; const selected=typeof detail==="string"?detail:new URLSearchParams(window.location.search).get("interest"); if(selected&&["start","clasic","full_social","free_ideas","unsure"].includes(selected)) setInterest(selected as LeadInterest); }; sync(); window.addEventListener("sans-retour-interest",sync); return()=>window.removeEventListener("sans-retour-interest",sync); },[]);
 async function handleSubmit(event:FormEvent<HTMLFormElement>){ event.preventDefault(); const form=event.currentTarget; const values=new FormData(form); setState("sending"); try{ await submitLeadForm({formType:"contact",interest,name:String(values.get("name")??""),businessName:String(values.get("businessName")??""),email:String(values.get("email")??""),phone:String(values.get("phone")??""),message:String(values.get("message")??""),consent:true,websiteTrap:String(values.get("companyWebsite")??"")} satisfies LeadInput,sendLead); form.reset(); setInterest("clasic"); setConsent(false); setState("success"); }catch{setState("error");}}
 return <form onSubmit={handleSubmit} className="space-y-5"><Input className={fieldClass} name="name" placeholder={t.name} required minLength={2} maxLength={100} autoComplete="name"/><Input className={fieldClass} name="businessName" placeholder={t.business} maxLength={120}/><div><Label htmlFor="contact-interest" className="mb-2 block text-xs tracking-[0.12em] text-muted-foreground">{t.interest}</Label><select id="contact-interest" name="interest" value={interest} onChange={e=>setInterest(e.target.value as LeadInterest)} className="h-12 w-full rounded-none border-x-0 border-t-0 border-input bg-transparent px-0 text-sm text-foreground outline-none focus:border-gold"><option value="start">ESSENTIAL — 1.500 LEI</option><option value="clasic">ELITE — 2.500 LEI</option><option value="full_social">BLACK ROYAL — 4.500 LEI</option><option value="free_ideas">{t.free}</option><option value="unsure">{t.talk}</option></select></div><div className="grid gap-5 sm:grid-cols-2"><Input className={fieldClass} name="email" placeholder="Email *" required type="email" maxLength={255} autoComplete="email"/><Input className={fieldClass} name="phone" placeholder={t.phone} type="tel" maxLength={40} autoComplete="tel"/></div><Textarea name="message" placeholder={t.message} required maxLength={2000} className="min-h-32 rounded-none border-x-0 border-t-0 px-0 focus-visible:border-gold focus-visible:ring-0"/><div className="hidden" aria-hidden="true"><Input name="companyWebsite" tabIndex={-1} autoComplete="off"/></div><div className="flex items-start gap-3"><Checkbox id={`contact-consent-${locale}`} checked={consent} onCheckedChange={v=>setConsent(v===true)} required/><Label htmlFor={`contact-consent-${locale}`} className="font-normal leading-relaxed text-muted-foreground">{t.consent}</Label></div><Button type="submit" size="lg" disabled={state==="sending"||!consent} className="h-13 rounded-none px-7 tracking-[0.12em]">{state==="sending"?t.sending:t.send}{state==="success"?<Check/>:<ArrowUpRight/>}</Button><FormStatus state={state} locale={locale}/></form>;
}
